## Mapping of diseases and drugs

In [21]:
import pandas as pd
from utils._path import processed_map_prefix, read_prefix, term_path
from utils._tools import read_data, write2file
import os
from os.path import join

In [16]:
# ## mapping of drugs
# joint_lda_prefix="/data/liu/mimic3/LDA_MODEL/JOINT_LDA/ngib700_ncomp10_gama0.01_alpha0.01"
# ndc_cui_map = read_data(join(processed_map_prefix,"rxnorm_ndc_df"),
#                         dtype={"CODE":str,'CUI_CODE':str}).drop_duplicates()
# ndc_cui_map = ndc_cui_map.set_index('CODE')['CUI_CODE'].to_dict()
# pres_df_ndc=read_data(join(read_prefix,'PRESCRIPTIONS'),dtype={'SUBJECT_ID':str,'HADM_ID':str,'NDC':str},\
#                 usecols=['NDC']).drop_duplicates().dropna(subset=['NDC'])
# pres_df_ndc=pres_df_ndc[pres_df_ndc['NDC']!='0']
# pres_df_ndc['RxNorm']=pres_df_ndc['NDC'].apply(lambda x: ndc_cui_map.get(x, None))
# write2file(pres_df_ndc,join(processed_map_prefix,"mimic3_ndc_rxnorm"))
# pres_df_ndc.head()

           NDC  RxNorm
0  00469061711  108513
1  00056017275  855334
2  00338055002    None
4  00054829725  310429
5  00056016975  855290

In [14]:
mimic3_ndc_rxnorm = read_data(join(processed_map_prefix,"mimic3_ndc_rxnorm"),dtype=str)
mimic3_ndc_rxnorm.head(10)

           NDC  RxNorm
0  00469061711  108513
1  00056017275  855334
2  00338055002     NaN
3  00054829725  310429
4  00056016975  855290
5  00338055002     NaN
6  00338055002     NaN
7  00056017075  855304
8  00469065773  108514
9  00469061711  108513

In [22]:
# ## mapping of diseases
# read_dtype={"SUBJECT_ID":str,"HADM_ID":str,"ICD9_CODE":str}
# icd9_cui_df = read_data(join(term_path, 'MRCONSO_ICD9CM_AB'),dtype=str)
# icd9_cui_dict=dict(zip(icd9_cui_df["CODE"],icd9_cui_df["CUI"]))
# diag_icd9_df = read_data(join(
#     read_prefix,"DIAGNOSES_ICD"),
#     dtype=read_dtype)[["ICD9_CODE"]].drop_duplicates().dropna(subset=["ICD9_CODE"])    
# diag_icd9_df=diag_icd9_df.assign(CUI=diag_icd9_df["ICD9_CODE"].apply(icd9_cui_dict.get))
# write2file(diag_icd9_df,join(processed_map_prefix,"mimic3_icd9_cui"))
# diag_icd9_df.head()

  ICD9_CODE       CUI
0     40301  C1719461
1       486  C0339951
2     58281  C0156234
3      5855  C1561642
4      4254  C0340419

In [23]:
mimic3_icd9_cui = read_data(join(processed_map_prefix,"mimic3_icd9_cui"),dtype=str)
mimic3_icd9_cui.head(10)

  ICD9_CODE       CUI
0     40301  C1719461
1       486  C0339951
2     58281  C0156234
3      5855  C1561642
4      4254  C0340419
5      2762  C0001122
6      7100  C0024141
7      2767  C0020461
8      7243  C0036396
9     45829  C1260414